version: 0.2
env:
  variables:
    S3_BUCKET: "ab-movies-api-deployment-packages"
    PACKAGE: "github.com/abeatrice/movies"
phases:
  install:
    commands:
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
  pre_build:
    commands:
      - cd "/go/src/${PACKAGE}"
      - cd index
      - go get .
      - golint
      - go test .
