version: 0.2
env:
  variables:
    S3_BUCKET: "ab-movies-api-deployment-packages"
    PACKAGE: "github.com/abeatrice/movies"
phases:
  install:
    commands:
      - echo "CODEBUILD_WEBHOOK_BASE_REF ${CODEBUILD_WEBHOOK_BASE_REF}"
      - echo "CODEBUILD_SOURCE_VERSION ${CODEBUILD_SOURCE_VERSION}"
      - echo "CODEBUILD_WEBHOOK_MERGE_COMMIT ${CODEBUILD_WEBHOOK_MERGE_COMMIT}"
      - echo "CODEBUILD_WEBHOOK_TRIGGER ${CODEBUILD_WEBHOOK_TRIGGER}"
      - |
        if [[ "${CODEBUILD_WEBHOOK_BASE_REF}" == "master" ]]; then
          echo "codebuild webhook base ref is master"
        else
          echo "codebuild webhook base ref is not master"
        fi
